### ISSUE TITLE
Add new feature: Support --config with config file

### ISSUE THREAD

**Issue by hlavu** [tuanthanh2067/cv-ssg#21]
Hi Thanh, I would like to add a new option `-c` or `--config` to your repo. This allows users to specify a config file storing options' values. 
By doing so, a user could run the SSG in 2 ways:

#1: 
`ssg --input ./site --output ./build --stylesheet https://cdn.jsdelivr.net/npm/water.css@2/out/water.css --lang fr`

#2: 
`ssg --config ./ssg-config.json`

ssg-config.json content:
`{
  "input": "./site",
  "output": "./build",
  "stylesheet": "https://cdn.jsdelivr.net/npm/water.css@2/out/water.css",
  "lang": "fr"
}`

#Tasks:
- [ ] The -c or --config flags accept a file path to a JSON config file.

- [ ] If the file is missing, or can't be parsed as JSON, exit with an appropriate error message.

- [ ] If the -c or --config option is provided, ignore all other options (i.e., a config file overrides other options on the command line).

- [ ] The program should ignore any options in the config file it doesn't recognize. For example, if the SSG doesn't support stylesheets, ignore a stylesheet property.

- [ ] If the config file is missing any options, assume the usual defaults. For example, use dist/ as the output directory if it isn't specified.

**Comment by tuanthanh2067** [comment]
That sounds great, go for it!

**Comment by tuanthanh2067** [comment]
Closed by #22
